name: Backend Tests

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./bugtracker-backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Execution Time
        run: echo "Execution Time: $(date '+%Y-%m-%d %H:%M:%S')"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./bugtracker-backend/go.mod

      - name: Download dependencies
        run: go mod download

      - name: Run Backend Tests
        run: go test ./...
